stateDiagram-v2
    direction LR

    [*] --> Pendente : Cliente inicia o checkout

    Pendente --> Processando : Pagamento aprovado
    Processando --> Enviado : Fornecedor despacha o produto
    Enviado --> [*] : (Fim do fluxo atual)

    %% Caminhos alternativos
    Pendente --> Cancelado : Falha no pagamento
    Processando --> Cancelado : Cliente solicita ou Estoque falha
    Cancelado --> [*]